// <auto-generated />
using System;
using BTCPayServer.Plugins.VAT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable enable

namespace BTCPayServer.Plugins.VAT.Data.Migrations;

[DbContext(typeof(VATDbContext))]
partial class VATDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("BTCPayServer.Plugins.VAT")
            .HasAnnotation("ProductVersion", "8.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("BTCPayServer.Plugins.VAT.Data.Models.VATEvidence", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<DateTimeOffset>("CollectedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<decimal>("Confidence")
                .HasColumnType("numeric(3,2)");

            b.Property<string>("CountryCode")
                .IsRequired()
                .HasMaxLength(2)
                .HasColumnType("character varying(2)");

            b.Property<string>("RawData")
                .HasColumnType("text");

            b.Property<int>("Type")
                .HasColumnType("integer");

            b.Property<string>("VATInvoiceRecordId")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.HasKey("Id");

            b.HasIndex("VATInvoiceRecordId");

            b.ToTable("VATEvidence", "BTCPayServer.Plugins.VAT");
        });

        modelBuilder.Entity("BTCPayServer.Plugins.VAT.Data.Models.VATInvoiceRecord", b =>
        {
            b.Property<string>("InvoiceId")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Currency")
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnType("character varying(10)");

            b.Property<string>("CustomerCountry")
                .IsRequired()
                .HasMaxLength(2)
                .HasColumnType("character varying(2)");

            b.Property<string>("CustomerVATNumber")
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<string>("EvidenceJson")
                .HasColumnType("text");

            b.Property<decimal>("GrossAmount")
                .HasColumnType("numeric(18,8)");

            b.Property<int>("ModeApplied")
                .HasColumnType("integer");

            b.Property<decimal>("NetAmount")
                .HasColumnType("numeric(18,8)");

            b.Property<bool>("ReverseChargeApplied")
                .HasColumnType("boolean");

            b.Property<string>("StoreId")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<decimal>("VATAmount")
                .HasColumnType("numeric(18,8)");

            b.Property<decimal>("VATRate")
                .HasColumnType("numeric(5,2)");

            b.HasKey("InvoiceId");

            b.HasIndex("CreatedAt");

            b.HasIndex("CustomerCountry");

            b.HasIndex("StoreId");

            b.HasIndex("StoreId", "CreatedAt");

            b.ToTable("VATInvoiceRecords", "BTCPayServer.Plugins.VAT");
        });

        modelBuilder.Entity("BTCPayServer.Plugins.VAT.Data.Models.VATStoreSettings", b =>
        {
            b.Property<string>("StoreId")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<bool>("BelowSmallBusinessThreshold")
                .HasColumnType("boolean");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<bool>("Enabled")
                .HasColumnType("boolean");

            b.Property<string>("HomeCountry")
                .IsRequired()
                .HasMaxLength(2)
                .HasColumnType("character varying(2)");

            b.Property<int>("Mode")
                .HasColumnType("integer");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("VATNumber")
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<bool>("ValidateVIES")
                .HasColumnType("boolean");

            b.HasKey("StoreId");

            b.HasIndex("StoreId")
                .IsUnique();

            b.ToTable("VATStoreSettings", "BTCPayServer.Plugins.VAT");
        });

        modelBuilder.Entity("BTCPayServer.Plugins.VAT.Data.Models.VATEvidence", b =>
        {
            b.HasOne("BTCPayServer.Plugins.VAT.Data.Models.VATInvoiceRecord", "VATInvoiceRecord")
                .WithMany("Evidence")
                .HasForeignKey("VATInvoiceRecordId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("VATInvoiceRecord");
        });

        modelBuilder.Entity("BTCPayServer.Plugins.VAT.Data.Models.VATInvoiceRecord", b =>
        {
            b.Navigation("Evidence");
        });
#pragma warning restore 612, 618
    }
}
